### ISSUE TITLE
publish latest version 3.7.10 to hex.pm

### ISSUE THREAD

**Issue by velimir** [rabbitmq/rabbitmq-erlang-client#115] opened 2019-01-17 11:56 UTC
currently latest available release 3.7.10 is not yet available on hex.pm:

<img width="819" alt="image" src="https://user-images.githubusercontent.com/709160/51317140-b18ba100-1a4e-11e9-9c8e-5981b2ac86de.png">

Website refers to the unknown version https://github.com/rabbitmq/rabbitmq-website/blob/f66fb36f6cfafd50c9fc00abcdb1d372da03ea25/site/rabbit.ent#L22

**Comment by michaelklishin** [comment] 2019-01-17 14:45
Consider looking through the issues before you file. Duplicate of #113.

**Closed by michaelklishin** 2019-01-17 14:45 UTC

**Comment by michaelklishin** [comment] 2019-01-31 17:38
[`3.7.11`](https://hex.pm/packages/amqp_client/3.7.11) is out.
